### PR TITLE
Reformat messages

### PR DESCRIPTION
**Pull request by jangrewe**
This will send messages in the format:

**[.STATUS] .CommonAnnotations.summary** (.CommonLabels[0] .CommonLabels[n]) 
.CommonAnnotations.description
**.Labels[0].key**: .Labels[0].value
**.Labels[n].key**: .Labels[n].value
`--`
**[.STATUS] .CommonAnnotations.summary** (.CommonLabels[0] .CommonLabels[n]) 
.CommonAnnotations.description
**.Labels[0].key**: .Labels[0].value
**.Labels[n].key**: .Labels[n].value

As i can't get any **working** Python2 environment up (the SSLv3 handshake problem), i'm afraid this is Python3-only. Maybe it's time to update, Python2 is deprecated anyways! ;-)

### CODE REVIEW

**Comment by jelmer** [comment]
This makes the messages a lot more verbose; is there a particular reasoning behind this formatting rather than something else? 

This breaks the tests at the moment.

**Comment by jangrewe** [comment]
Yes, of course! This not only tells me that there was an alert, but also what exactly is causing the alert. It mimics the default Prometheus alert emails, at least regarding the included information. 

Before, the messages looked like this:
> ‎FIRING, 2019-05-17T18:48:18, SSL Cert Expiring in 30 days

Now they look like this:
> **[FIRING] SSL Cert Expiring in 30 days** (SSLExpire_30Days ssl warning) 
> The SSL certificate for **example.com:443** will expire in **25d 7h 53m 58s**.
> **alertname:** SSLExpire_30Days
> **instance:** example.com:443
> **issuer_cn:** Let's Encrypt Authority X3
> **job:** ssl
> **serial_no:** 308924514759606019817880538855731795119738
> **severity:** warning

With only the alert name and status, i will have to check in Prometheus or alertmanager or any other receiver first to find out what's going no. With this more verbose format, i have all available details right away.

There are some minor things i'd like to improve, like using the GroupLabels instead of CommonLabels, and maybe add a config option to toggle between short and full alert format (or even templating?), but for me this detailed format is a hard requirement! ;-)

**Comment by jangrewe** [comment]
Whoops, didn't even see there were tests... they're fixed now, and the message format can be switched from the old, short format to the additional (optional, to maintain backwards compatibility) full detailed format.

**Comment by jelmer** [comment]
Merged, thanks!

**Pull request closed without merging**
